# NumPy Tutorial

Numpy մոդուլը հնարավորություն է տալիս ստեղծել բազմաչափ զանգվածներ (array) և դրանց հետ գործողություններ կատարել։ Անունը բացվում է որպես 'Numerical Python'.

NumPy-ով հնարավոր է մաթեմատիկական և տրամաբանական գործողություններ մասիվների վրա, գծային հանրահաշվական գործողություններ կատարել, գեներացնել պատահական թվեր, Ֆուրիեյի տրանսֆորմացիաներ և այլն։


NumPy-ը տվյալագիտության մեջ գործածվող հիմնական գրադարաններից է։

# Lists VS Numpy

NumPy զանգվածները չափսերով ավելի փոքր են, դրանց հետ գործողություններն արագ են, ունեն ֆիքսված չափ հիշողության մեջ և չեն կարող պարունակել տարբեր տիպեր։ Ի տարբերություն, Պիտոնի լիստերը չունեն ֆիքսված չափ, դրանք կարող են դինամիկ կերպով փոխվել։ Դրանց մեջ կարելի է նաև պահել տարբեր տիպերի փոփոխականներ։

Ինստալյացիան՝
```
pip3 install numpy
conda install numpy
```

Եկեք իմպորտ անենք մոդուլը

In [1]:
import numpy as np
import timeit

In [2]:
arr_1 = np.arange(1000)
arr_2 = np.arange(1000)

start = timeit.default_timer()
arr_1 + arr_2
print(f'Run time is: {timeit.default_timer() - start}')

Run time is: 0.006239875000119355


In [3]:
list_1 = list(range(1000))
list_2 = list(range(1000))

start = timeit.default_timer()
[i + j for i, j in zip(list_1, list_2)]
print(f'Run time is: {timeit.default_timer() - start}')

Run time is: 0.005114390000017011


In [4]:
list_1 = [2, 4, 8]
list_2 = [1, 2, 3]

list(zip(list_1, list_2))

for i, j in list(zip(list_1, list_2)):
  print(i + j)

3
6
11


In [5]:
for i, j in enumerate(list_1):
  print(i, j)

0 2
1 4
2 8


 NumPy-ի ամենակարևոր օբյեկտը ndarray-ն է (N-dimensional array)։ Դա կարող է պարունակել նույն տիպի արժեքներ։ 


In [6]:
arr = np.array(list_1)

In [7]:
arr

array([2, 4, 8])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int64')

In [10]:
mixed_arr = np.array([1, 2, 3, 5.6, True, 'String'])

In [11]:
mixed_arr.dtype

dtype('<U32')

In [12]:
mixed_arr

array(['1', '2', '3', '5.6', 'True', 'String'], dtype='<U32')

In [13]:
print(type(mixed_arr[0]))

<class 'numpy.str_'>


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
type(lst)

list

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)


In [18]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float16)


In [20]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)

# Array attributes

### ndarray.shape

In [21]:
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)

In [22]:
arr.shape

(3, 3)

shape ատրիբուտը ցույց է տալիս զանգվածի կառուցվածքը (տողերի և սյուների քանակը) որպես tuple։ Shape-ը բացահայտ փոփոխելով կարող ենք փոխել զանգվածի կառուցվածքը (եթե հնարավոր է)

In [23]:
arr.shape = (9, )

In [24]:
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [25]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
arr_1.shape

(2, 3)

Փոխենք չափողականությունը

In [27]:
arr_1.shape = (3, 2)

In [28]:
arr_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
arr_1.shape = (6, )
arr_1

array([1, 2, 3, 4, 5, 6])

Նույնը կարելի է անել **reshape()** մեթոդի օգնությամբ

In [30]:
arr_1.shape = (2, 3)
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr_1.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
arr_2 = np.arange(25)

In [33]:
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr_2.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### ndarray.ndim

ndim ատրիբուտը ցույց է տալիս զանգվածի չափողականությունը

In [35]:
arr_1.ndim

2

In [36]:
arr_1.reshape(6, ).ndim
arr_1.reshape(6, )

array([1, 2, 3, 4, 5, 6])

In [37]:
arr_2.reshape(5, 5, 1).ndim

3

In [38]:
arr_3 = np.arange(64)

In [39]:
arr_3.reshape(4, 4, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

### numpy.itemsize

itemsize-ը ցույց է տալիս, թե ինչքան տեղ են զբաղեցնում զանգվածի տարրերը (բայթերով)

In [40]:
arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr_1.dtype

dtype('int64')

In [42]:
arr_1.itemsize

8

In [45]:
import sys

lst = list(range(10000000))
arr = np.arange(10000000)

print(f'Python list size: {sys.getsizeof(lst)} bytes')
print(f'Numpy ndarray size: {sys.getsizeof(arr)} bytes')

Python list size: 90000120 bytes
Numpy ndarray size: 80000096 bytes


# Array creation

### numpy.empty(shape, dtype = float)

Ստեղծում է տրված կառուցվածքով դատարկ զանգված, որի տարրերը dtype-ով որոշվող տիպի են 

In [69]:
empty = np.empty((4, 4))

In [81]:
empty

array([[4.68496295e-310, 1.03977794e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.16709769e-312, 1.03977794e-312, 1.23075756e-312,
        1.08221785e-312],
       [1.06099790e-312, 9.76118064e-313, 1.06099790e-312,
        1.03977794e-312],
       [1.08221785e-312, 4.44659081e-322, 0.00000000e+000,
        0.00000000e+000]])

In [50]:
empty.dtype

dtype('float64')

In [51]:
empty_1 = np.empty((4, 4), dtype=np.str)

In [52]:
empty_1

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [53]:
empty_1 = np.empty((4, 4), dtype=np.bool)

empty_1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
empty_1 = np.empty((4, 4), dtype=int)

print(empty_1)

[[           0 210453397554 206158430253 193273528377]
 [236223201328 210453397588 249108103222 214748364849]
 [210453397562 197568495670 219043332147 240518168625]
 [214748364852           90            0            0]]


### numpy.zeros(shape, dtype = float)  

Ստեղծղում է տրված կառուցվածքի զանգված և լցնում այն 0-ներով

In [91]:
zeros = np.zeros((4, 4))

In [92]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
zeros.dtype

dtype('float64')

In [94]:
zeros = np.zeros((4, 4), dtype=int)

In [97]:
zeros.dtype

dtype('int64')

In [98]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [100]:
x = 5.
print(x)
print(type(x))

5.0
<class 'float'>


### numpy.ones(shape, dtype = None, order = 'C')

Ստեղծղում է տրված կառուցվածքի զանգված և լցնում այն 1-երով

In [109]:
ones = np.ones((4, 4))

In [111]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [112]:
ones = np.ones((4, 4), dtype=str)

In [113]:
ones

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [114]:
ones = np.ones((4, 4), dtype=np.int16)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int16)

## Create an array from existing data

### numpy.asarray(a, dtype = None)
a-ն կարող է լինել լիստ, tuple, լիստերի լիստ, լիստերի tuple և այլն

In [123]:
lst.append('f')

In [125]:
arr = np.asarray(lst)

In [126]:
arr

array(['1', '2', '3', '4', '5', '6', 'f'], dtype='<U21')

### Repeating the values

**tile()** մեթոդը թույլ է տալիս կրկնել զանգվածի պարունակությունը 

In [127]:
a = np.asarray([1, 2, 3, 4])

In [128]:
a_1 = np.tile(a, 3)

print(a_1)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [129]:
a_1 = np.tile(a, (3, 3))

In [130]:
a_1

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [131]:
a = np.array([np.nan])

In [133]:
a = np.array([np.inf])
a

array([inf])

## Create an array from numerical ranges

### numpy.arange(start, stop, step, dtype)

Վերադարձնում է [start, stop) տիրույթում իրարից step չափով հեռացված թվերի զանգված 

In [140]:
arange = np.arange(1, 100, 2)

In [141]:
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### numpy.linspace(start, stop, num, endpoint, retstep, dtype)

Վերադարձնում է զանգված, որը պարունակում է [start, stop] տիրույթում num քանակի իրարից հավասարաչափ հեռացված արժեքներ։

In [162]:
linspace = np.linspace(0, 100, 5)
linspace

array([  0.,  25.,  50.,  75., 100.])

Եթե еndpoint=True, ապա, տիրույթը փակվում է` [start, stop]

In [166]:
linspace = np.linspace(0, 100, 100000, endpoint=False, retstep=True)
print(linspace[0][6])
print(len(linspace[0]))
print(linspace[1])


0.006
100000
0.001


retstep-ը True-ի դեպքում, վերադարձվում է նաև քայլի չափսը։

In [171]:
linspace, step = np.linspace(0, 100, 50, retstep=True)

In [172]:
step

2.0408163265306123

In [173]:
linspace

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

# Indexing and slicing


### slice(start, stop, step)

**slice()** ֆունկցիան թույլ է տալիս ստանալ զանգվածների, սթրինգերի, լիստերի որոշակի հատված

In [177]:
arr = np.arange(50, 200)

chunk = slice(2, 30)

print(arr[chunk])
print(arr[2:30])
print(arr[2], arr[29])


[52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79]
[52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75
 76 77 78 79]
52 79


## Indexing of multi-dimensional ndarrays

In [178]:
lst = [[i * j for i in range(6)] for j in range(6)]

lst

[[0, 0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4, 5],
 [0, 2, 4, 6, 8, 10],
 [0, 3, 6, 9, 12, 15],
 [0, 4, 8, 12, 16, 20],
 [0, 5, 10, 15, 20, 25]]

In [179]:
lst[2][3]

6

In [180]:
[lst[i][3] for i in range(len(lst))]

[0, 3, 6, 9, 12, 15]

In [182]:
arr = np.array(lst)

In [183]:
arr

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20],
       [ 0,  5, 10, 15, 20, 25]])

In [184]:
arr[2, 3]

6

In [185]:
arr[:, 3]

array([ 0,  3,  6,  9, 12, 15])

In [191]:
arr[:, -1]

array([[ 0,  0,  0,  0],
       [ 2,  3,  4,  5],
       [ 4,  6,  8, 10],
       [ 6,  9, 12, 15],
       [ 8, 12, 16, 20],
       [10, 15, 20, 25]])

In [192]:
arr[2:4, 1:3]

array([[2, 4],
       [3, 6]])

Ավելի մանրամասն՝

https://numpy.org/doc/stable/reference/arrays.indexing.html

## Using Numpy with Conditional Expressions

In [193]:
arr = np.arange(100)

print('Evens: ', arr[arr % 2 == 0])

Evens:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [194]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [195]:
print(arr[arr >= 50])

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [196]:
arr >= 50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [197]:
bad_array = np.array([1, 2, 3, 4, np.nan, 4, 5, 2, np.nan, np.nan])

In [202]:
np.isnan(bad_array)

bad_array[np.isnan(bad_array)]

array([nan, nan, nan])

In [209]:
# In numpy 'and' is &, 'or' is |

print(arr[((arr >= 50) & (arr % 2 == 1))])

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


In [206]:
arr[arr > 50].sum()

3675

## Find index of a value

In [210]:
arr = np.arange(50, 200)

In [212]:
b = np.where(arr % 3 == 0)
b

(array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
         40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
         79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
        118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148]),)

In [213]:
arr[b]

array([ 51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,  84,  87,
        90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123, 126,
       129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
       168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198])

In [214]:
arr[arr % 3 == 0]

array([ 51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,  84,  87,
        90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123, 126,
       129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
       168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198])

# Arithmetic operations

In [227]:
a = np.arange(10)
b = np.arange(10, 20)

print('First array: ', a)
print('Second array: ', b)
print('Sum array: ', a + b)
print('=' * 100)

print('Sum array: ', np.add(a, b))

First array:  [0 1 2 3 4 5 6 7 8 9]
Second array:  [10 11 12 13 14 15 16 17 18 19]
Sum array:  [10 12 14 16 18 20 22 24 26 28]
Sum array:  [10 12 14 16 18 20 22 24 26 28]


In [225]:
a = np.arange(10)
b = np.arange(10, 20)

print('First array: ', a)
print('Second array: ', b)
print('Dif array: ', a - b)
print('=' * 100)

print('Dif array: ', np.subtract(a, b))

First array:  [0 1 2 3 4 5 6 7 8 9]
Second array:  [10 11 12 13 14 15 16 17 18 19]
Dif array:  [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Dif array:  [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]


In [223]:
a = np.arange(10)
b = np.arange(10, 20)

print('First array: ', a)
print('Second array: ', b)
print('Mult array: ', a * b)
print('=' * 100)

print('Mult array: ', np.multiply(a, b))

First array:  [0 1 2 3 4 5 6 7 8 9]
Second array:  [10 11 12 13 14 15 16 17 18 19]
Mult array:  [  0  11  24  39  56  75  96 119 144 171]
Mult array:  [  0  11  24  39  56  75  96 119 144 171]


In [222]:
a = np.arange(10)
b = np.arange(10, 20)

print('First array: ', a)
print('Second array: ', b)
print('Div array: ', b / a)
print('=' * 100)
print('Div array: ', np.divide(b, a))

print('The rest of our code')

First array:  [0 1 2 3 4 5 6 7 8 9]
Second array:  [10 11 12 13 14 15 16 17 18 19]
Div array:  [        inf 11.          6.          4.33333333  3.5         3.
  2.66666667  2.42857143  2.25        2.11111111]
Div array:  [        inf 11.          6.          4.33333333  3.5         3.
  2.66666667  2.42857143  2.25        2.11111111]
The rest of our code


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


# Some matrix operations

## numpy.dot
Սկալար արտադրյալ կամ մատրիցների արտադրյալ

$$u*v = u_1v_1 + u_2v_2$$

$$C_{i, j} = \sum A_{i, d} * B_{d, i}$$

In [228]:
a = np.arange(10)
b = np.arange(10, 20)

print('First array: ', a)
print('Second array: ', b)
print('Div array: ', b @ a)
print('=' * 100)
print('Div array: ', np.dot(b, a))

First array:  [0 1 2 3 4 5 6 7 8 9]
Second array:  [10 11 12 13 14 15 16 17 18 19]
Div array:  735
Div array:  735


## numpy.linalg.det

Վերադարձնում է մատրիցի որոշիչը

In [238]:
arr = np.array([[1, 0, 3], [4, 6, 2], [5, 1, 2]])

arr

array([[1, 0, 3],
       [4, 6, 2],
       [5, 1, 2]])

In [239]:
np.linalg.det(arr)

-67.99999999999996

## np.linalg.inv

Վերադարձնում է տրված մատրիցի հակադարձը

In [240]:
np.linalg.inv(arr)

array([[-0.14705882, -0.04411765,  0.26470588],
       [-0.02941176,  0.19117647, -0.14705882],
       [ 0.38235294,  0.01470588, -0.08823529]])

## Transpose of a matrix

Տրանսպոնացնում է մատրիցը

In [244]:
print(arr.T)
print('=' * 100)
print(arr)

[[1 4 5]
 [0 6 1]
 [3 2 2]]
[[1 0 3]
 [4 6 2]
 [5 1 2]]


In [245]:
print(arr.transpose())
print('=' * 100)
print(arr)

[[1 4 5]
 [0 6 1]
 [3 2 2]]
[[1 0 3]
 [4 6 2]
 [5 1 2]]


In [256]:
np.rot90(arr, axes=(1, 0))

array([[5, 4, 1],
       [1, 6, 0],
       [2, 2, 3]])

In [261]:
np.rot90(arr, -1)

array([[5, 4, 1],
       [1, 6, 0],
       [2, 2, 3]])

## np.diag

Վերադարձնում է անկյունագծի տարրերը

In [263]:
arr

array([[1, 0, 3],
       [4, 6, 2],
       [5, 1, 2]])

In [262]:
np.diag(arr)

array([1, 6, 2])

## Random numbers

**rand(n)**-ը վերադարձնում է [0, 1) միջակայքում n պատահական թիվ/թվերի զանգված

In [264]:
rand = np.random.rand(10)

rand

array([0.08734323, 0.64008735, 0.72200197, 0.27786273, 0.78258704,
       0.69415275, 0.24625949, 0.12321971, 0.51631694, 0.48757022])

**randint(a, b, n)** վերադարձնում է [a, b) միջակայքում n պատահական թիվ/թվերի զանգված

In [265]:
randints = np.random.randint(0, 200, 10)

randints

array([134, 130,  90,  28,  45,  48,  73,  62, 121, 116])

In [266]:
normal = np.random.normal(10, 0.5, 100)
print(normal)

[ 8.5994604  11.08056926  9.61611164  9.72845389  9.85159511 10.64419584
  9.51801596 10.39726471  9.78442574 10.48884789  9.277263    9.69812679
 10.38362152  9.64371594  9.80773434  9.55463369  9.92119845 10.75128079
 10.65358854  9.41902968  9.83535088  9.25447314 10.05151463  9.68674621
 10.24384319  9.34757912 10.33717605  9.89645932 10.4241296   9.69918959
  9.82267678 10.27833365 10.72994966  8.68580094 10.67013779  9.46422592
 10.74985221 10.21826285 10.23853868 10.34760074  9.70611865  8.97647297
 10.43258623  9.75140286  9.56953398 10.69841863 11.25280976 10.13368249
 10.35527119 10.25213558 10.12486229  9.55413405 10.30138397 10.85842186
  9.5811398  10.08610032  9.53935111 10.37815083  9.51358778  9.19306362
  9.56182084 10.10027885 11.03261458 10.22068307 10.12378119 10.95216509
 10.49078267 10.86389774  9.97302647  9.66536645  8.79626309 10.61572239
  9.60994331 10.50495773  9.33572758  9.23865795 10.78539811 10.93941292
  9.95441656  9.84435502  9.55256362  9.95369166  9

In [277]:
np.random.seed(54)

rand_arr = np.random.randint(0, 10, 10)
print(rand_arr)

[5 2 7 1 0 8 7 1 9 6]


# Mathematical functions

## Trigonometry

In [278]:
import math

In [280]:
print('Math pi: ', math.pi)
print('Numpy pi: ', np.pi)

print('Math e: ', math.e)
print('Numpy e: ', np.e)

Math pi:  3.141592653589793
Numpy pi:  3.141592653589793
Math e:  2.718281828459045
Numpy e:  2.718281828459045


In [286]:
angles = np.array([30, 45, 60, 90])

print(np.sin(np.radians(angles)))
print(np.sin(angles / 180 * np.pi))

print('=' * 100)

print(np.cos(np.radians(angles)))
print(np.cos(angles / 180 * np.pi))
print('=' * 100)
print(np.tan(np.radians(angles)))
print(np.tan(angles / 180 * np.pi))


[0.5        0.70710678 0.8660254  1.        ]
[0.5        0.70710678 0.8660254  1.        ]
[8.66025404e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]
[8.66025404e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]
[5.77350269e-01 1.00000000e+00 1.73205081e+00 1.63312394e+16]
[5.77350269e-01 1.00000000e+00 1.73205081e+00 1.63312394e+16]


## Functions for Rounding

**around()** կլորացնում է փոխանցված զանգվածի տարրերը

In [289]:
a = np.array([1.555543, np.pi, np.e, 6.7888])

print(np.around(a))
print(np.around(a, decimals=2))

[2. 3. 3. 7.]
[1.56 3.14 2.72 6.79]


**floor()** կլորացնում է դեպի ներքև

In [290]:
np.floor(a)

array([1., 3., 2., 6.])

**ceil()** կլորացնում է դեպի վերև

In [291]:
np.ceil(a)

array([2., 4., 3., 7.])

## Statistical functions

**amin()** վերադարձնում է զանգվածի նվազագույն տարրը։ Բացահայտ նշելով axis պարամետրի արժեքը, վերադարձնում է բոլոր սյուների/տողերի նվազագույն արժեքները

In [295]:
arr = np.array([[4, 1, 2], [7, 2, 8], [6, 2, 4]])

np.amin(arr, axis=1)
np.amin(arr, axis=0)


array([4, 1, 2])

**median()** վերադարձնում է մեդիանը (մեջտեղի արժեքը)

In [296]:
np.median(arr)

4.0

**mean()** վերադարձնում է զանգվածի միջին արժեքը

In [299]:
print(np.mean(arr, axis=0))

print(np.mean(arr, axis=1))



[5.66666667 1.66666667 4.66666667]
[2.33333333 5.66666667 4.        ]


```
Weighted average = (1*1+2*2+3*3+4*4)/(1+2+3+4)
```

**average()** վերադարձնում է զանգվածի միջինը։ Եթե կշիռները տրված են, ապա վերադարձնում է weighted միջինը։

In [314]:
grades = np.array([[4, 1, 2], [7, 2, 8], [6, 2, 4]]).flatten()
credits = np.arange(1, 10)

print(sum(grades) / len(grades))
print(np.average(grades, weights=credits))

4.0
4.266666666666667


In [311]:
print(grades)
print(credits)

[4 1 2 7 2 8 6 2 4]
[1 2 3 4 5 6 7 8 9]


**std()** վերադարձնում է միջին քառակուսային շեղումը։

$$std = \sqrt{mean(x - x.mean())^2}$$

In [315]:
np.std(grades)

2.3570226039551585

## Sort

**sort()** սորտավորում է զանգվածը։ axis-ը տալով, կարող ենք սորտավորել ըստ սյուների կամ ըստ տողերի։

In [316]:
grades = np.array([[4, 1, 2], [7, 2, 8], [6, 2, 4]])

In [319]:
print(np.sort(grades))
print('=' * 100)
print(np.sort(grades.flatten()))

[[1 2 4]
 [2 7 8]
 [2 4 6]]
[1 2 2 2 4 4 6 7 8]


In [321]:
print(np.sort(grades, axis=0))

[[4 1 2]
 [6 2 4]
 [7 2 8]]


# For further exploration 

Ավելի մանրամասն կարող եք կարդալ դոկումենտացիայում

https://numpy.org/doc/